load("@rules_cc//cc:cc_library.bzl", "cc_library")

arrow_srcs = [
    "arrow/buffer.cc",
    "arrow/buffer_test.cc",
    "arrow/builder.cc",
    "arrow/builder_benchmark.cc",
    "arrow/chunk_resolver.cc",
    "arrow/chunk_resolver_benchmark.cc",
    "arrow/chunked_array.cc",
    "arrow/chunked_array_test.cc",
    "arrow/compare.cc",
    "arrow/compare_benchmark.cc",
    "arrow/config.cc",
    "arrow/datum.cc",
    "arrow/datum_test.cc",
    "arrow/device.cc",
    "arrow/device_allocation_type_set.cc",
    "arrow/extension_type.cc",
    "arrow/extension_type_test.cc",
    "arrow/field_ref_test.cc",
    "arrow/memory_pool.cc",
    "arrow/memory_pool_benchmark.cc",
    "arrow/memory_pool_jemalloc.cc",
    "arrow/memory_pool_mimalloc.cc",
    "arrow/memory_pool_test.cc",
    "arrow/pretty_print.cc",
    "arrow/pretty_print_test.cc",
    "arrow/public_api_test.cc",
    "arrow/record_batch.cc",
    "arrow/record_batch_test.cc",
    "arrow/result.cc",
    "arrow/result_test.cc",
    "arrow/scalar.cc",
    "arrow/scalar_test.cc",
    "arrow/sparse_tensor.cc",
    "arrow/sparse_tensor_test.cc",
    "arrow/status.cc",
    "arrow/status_test.cc",
    "arrow/stl_iterator_test.cc",
    "arrow/stl_test.cc",
    "arrow/table.cc",
    "arrow/table_builder.cc",
    "arrow/table_builder_test.cc",
    "arrow/table_test.cc",
    "arrow/tensor.cc",
    "arrow/tensor_benchmark.cc",
    "arrow/tensor_test.cc",
    "arrow/type.cc",
    "arrow/type_benchmark.cc",
    "arrow/type_test.cc",
    "arrow/type_traits.cc",
    "arrow/visitor.cc",
]

arrow_hdrs = [
    "arrow/api.h",
    "arrow/array.h",
    "arrow/buffer.h",
    "arrow/buffer_builder.h",
    "arrow/builder.h",
    "arrow/chunk_resolver.h",
    "arrow/chunked_array.h",
    "arrow/compare.h",
    "arrow/config.h",
    "arrow/datum.h",
    "arrow/device.h",
    "arrow/device_allocation_type_set.h",
    "arrow/extension_type.h",
    "arrow/memory_pool.h",
    "arrow/memory_pool_internal.h",
    "arrow/memory_pool_test.h",
    "arrow/pretty_print.h",
    "arrow/record_batch.h",
    "arrow/result.h",
    "arrow/scalar.h",
    "arrow/sparse_tensor.h",
    "arrow/status.h",
    "arrow/status_internal.h",
    "arrow/stl.h",
    "arrow/stl_allocator.h",
    "arrow/stl_iterator.h",
    "arrow/table.h",
    "arrow/table_builder.h",
    "arrow/tensor.h",
    "arrow/type.h",
    "arrow/type_fwd.h",
    "arrow/type_traits.h",
    "arrow/visit_array_inline.h",
    "arrow/visit_data_inline.h",
    "arrow/visit_scalar_inline.h",
    "arrow/visit_type_inline.h",
    "arrow/visitor.h",
    "arrow/visitor_generate.h",
]

array_srcs = [
    "arrow/array/array_base.cc",
    "arrow/array/array_binary.cc",
    "arrow/array/array_binary_test.cc",
    "arrow/array/array_decimal.cc",
    "arrow/array/array_dict.cc",
    "arrow/array/array_dict_test.cc",
    "arrow/array/array_list_test.cc",
    "arrow/array/array_list_view_test.cc",
    "arrow/array/array_nested.cc",
    "arrow/array/array_primitive.cc",
    "arrow/array/array_run_end.cc",
    "arrow/array/array_run_end_test.cc",
    "arrow/array/array_struct_test.cc",
    "arrow/array/array_test.cc",
    "arrow/array/array_union_test.cc",
    "arrow/array/array_view_test.cc",
    "arrow/array/builder_adaptive.cc",
    "arrow/array/builder_base.cc",
    "arrow/array/builder_binary.cc",
    "arrow/array/builder_decimal.cc",
    "arrow/array/builder_dict.cc",
    "arrow/array/builder_nested.cc",
    "arrow/array/builder_primitive.cc",
    "arrow/array/builder_run_end.cc",
    "arrow/array/builder_union.cc",
    "arrow/array/concatenate.cc",
    "arrow/array/concatenate_test.cc",
    "arrow/array/data.cc",
    "arrow/array/data_test.cc",
    "arrow/array/diff.cc",
    "arrow/array/diff_test.cc",
    "arrow/array/statistics.cc",
    "arrow/array/statistics_test.cc",
    "arrow/array/util.cc",
    "arrow/array/validate.cc",
]

array_hdrs = [
    "arrow/array/array_base.h",
    "arrow/array/array_binary.h",
    "arrow/array/array_decimal.h",
    "arrow/array/array_dict.h",
    "arrow/array/array_nested.h",
    "arrow/array/array_primitive.h",
    "arrow/array/array_run_end.h",
    "arrow/array/builder_adaptive.h",
    "arrow/array/builder_base.h",
    "arrow/array/builder_binary.h",
    "arrow/array/builder_decimal.h",
    "arrow/array/builder_dict.h",
    "arrow/array/builder_nested.h",
    "arrow/array/builder_primitive.h",
    "arrow/array/builder_run_end.h",
    "arrow/array/builder_time.h",
    "arrow/array/builder_union.h",
    "arrow/array/concatenate.h",
    "arrow/array/data.h",
    "arrow/array/dict_internal.h",
    "arrow/array/diff.h",
    "arrow/array/statistics.h",
    "arrow/array/util.h",
    "arrow/array/validate.h",
]

compute_srcs = [
    "arrow/compute/api_aggregate.cc",
    "arrow/compute/api_scalar.cc",
    "arrow/compute/api_vector.cc",
    "arrow/compute/benchmark_main.cc",
    "arrow/compute/cast.cc",
    "arrow/compute/exec.cc",
    "arrow/compute/exec_test.cc",
    "arrow/compute/expression.cc",
    "arrow/compute/expression_test.cc",
    "arrow/compute/function.cc",
    "arrow/compute/function_benchmark.cc",
    "arrow/compute/function_internal.cc",
    "arrow/compute/function_test.cc",
    "arrow/compute/initialize.cc",
    "arrow/compute/kernel.cc",
    "arrow/compute/kernel_test.cc",
    "arrow/compute/kernels/aggregate_basic.cc",
    "arrow/compute/kernels/aggregate_basic.inc.cc",
    "arrow/compute/kernels/aggregate_basic_avx2.cc",
    "arrow/compute/kernels/aggregate_basic_avx512.cc",
    "arrow/compute/kernels/aggregate_mode.cc",
    "arrow/compute/kernels/aggregate_pivot.cc",
    "arrow/compute/kernels/aggregate_quantile.cc",
    "arrow/compute/kernels/aggregate_tdigest.cc",
    "arrow/compute/kernels/aggregate_test.cc",
    "arrow/compute/kernels/aggregate_var_std.cc",
    "arrow/compute/kernels/chunked_internal.cc",
    "arrow/compute/kernels/codegen_internal.cc",
    "arrow/compute/kernels/codegen_internal_test.cc",
    "arrow/compute/kernels/hash_aggregate.cc",
    "arrow/compute/kernels/hash_aggregate_numeric.cc",
    "arrow/compute/kernels/hash_aggregate_pivot.cc",
    "arrow/compute/kernels/pivot_internal.cc",
    "arrow/compute/kernels/ree_util_internal.cc",
    "arrow/compute/kernels/scalar_arithmetic.cc",
    "arrow/compute/kernels/scalar_arithmetic_benchmark.cc",
    "arrow/compute/kernels/scalar_arithmetic_test.cc",
    "arrow/compute/kernels/scalar_boolean.cc",
    "arrow/compute/kernels/scalar_boolean_benchmark.cc",
    "arrow/compute/kernels/scalar_boolean_test.cc",
    "arrow/compute/kernels/scalar_cast_benchmark.cc",
    "arrow/compute/kernels/scalar_cast_boolean.cc",
    "arrow/compute/kernels/scalar_cast_dictionary.cc",
    "arrow/compute/kernels/scalar_cast_extension.cc",
    "arrow/compute/kernels/scalar_cast_internal.cc",
    "arrow/compute/kernels/scalar_cast_nested.cc",
    "arrow/compute/kernels/scalar_cast_numeric.cc",
    "arrow/compute/kernels/scalar_cast_string.cc",
    "arrow/compute/kernels/scalar_cast_temporal.cc",
    "arrow/compute/kernels/scalar_cast_test.cc",
    "arrow/compute/kernels/scalar_compare.cc",
    "arrow/compute/kernels/scalar_compare_benchmark.cc",
    "arrow/compute/kernels/scalar_compare_test.cc",
    "arrow/compute/kernels/scalar_if_else.cc",
    "arrow/compute/kernels/scalar_if_else_benchmark.cc",
    "arrow/compute/kernels/scalar_if_else_test.cc",
    "arrow/compute/kernels/scalar_list_benchmark.cc",
    "arrow/compute/kernels/scalar_nested.cc",
    "arrow/compute/kernels/scalar_nested_test.cc",
    "arrow/compute/kernels/scalar_random.cc",
    "arrow/compute/kernels/scalar_random_benchmark.cc",
    "arrow/compute/kernels/scalar_random_test.cc",
    "arrow/compute/kernels/scalar_round.cc",
    "arrow/compute/kernels/scalar_round_arithmetic_test.cc",
    "arrow/compute/kernels/scalar_round_benchmark.cc",
    "arrow/compute/kernels/scalar_set_lookup.cc",
    "arrow/compute/kernels/scalar_set_lookup_benchmark.cc",
    "arrow/compute/kernels/scalar_set_lookup_test.cc",
    "arrow/compute/kernels/scalar_string_ascii.cc",
    "arrow/compute/kernels/scalar_string_benchmark.cc",
    "arrow/compute/kernels/scalar_string_test.cc",
    "arrow/compute/kernels/scalar_string_utf8.cc",
    "arrow/compute/kernels/scalar_temporal_benchmark.cc",
    "arrow/compute/kernels/scalar_temporal_binary.cc",
    "arrow/compute/kernels/scalar_temporal_test.cc",
    "arrow/compute/kernels/scalar_temporal_unary.cc",
    "arrow/compute/kernels/scalar_validity.cc",
    "arrow/compute/kernels/scalar_validity_test.cc",
    "arrow/compute/kernels/select_k_test.cc",
    "arrow/compute/kernels/temporal_internal.cc",
    "arrow/compute/kernels/test_util_internal.cc",
    "arrow/compute/kernels/util_internal.cc",
    "arrow/compute/kernels/vector_array_sort.cc",
    "arrow/compute/kernels/vector_cumulative_ops.cc",
    "arrow/compute/kernels/vector_cumulative_ops_test.cc",
    "arrow/compute/kernels/vector_hash.cc",
    "arrow/compute/kernels/vector_hash_benchmark.cc",
    "arrow/compute/kernels/vector_hash_test.cc",
    "arrow/compute/kernels/vector_nested.cc",
    "arrow/compute/kernels/vector_nested_test.cc",
    "arrow/compute/kernels/vector_pairwise.cc",
    "arrow/compute/kernels/vector_pairwise_test.cc",
    "arrow/compute/kernels/vector_partition_benchmark.cc",
    "arrow/compute/kernels/vector_rank.cc",
    "arrow/compute/kernels/vector_replace.cc",
    "arrow/compute/kernels/vector_replace_benchmark.cc",
    "arrow/compute/kernels/vector_replace_test.cc",
    "arrow/compute/kernels/vector_run_end_encode.cc",
    "arrow/compute/kernels/vector_run_end_encode_test.cc",
    "arrow/compute/kernels/vector_select_k.cc",
    "arrow/compute/kernels/vector_selection.cc",
    "arrow/compute/kernels/vector_selection_benchmark.cc",
    "arrow/compute/kernels/vector_selection_filter_internal.cc",
    "arrow/compute/kernels/vector_selection_internal.cc",
    "arrow/compute/kernels/vector_selection_take_internal.cc",
    "arrow/compute/kernels/vector_selection_test.cc",
    "arrow/compute/kernels/vector_sort.cc",
    "arrow/compute/kernels/vector_sort_benchmark.cc",
    "arrow/compute/kernels/vector_sort_test.cc",
    "arrow/compute/kernels/vector_statistics.cc",
    "arrow/compute/kernels/vector_statistics_test.cc",
    "arrow/compute/kernels/vector_swizzle.cc",
    "arrow/compute/kernels/vector_swizzle_test.cc",
    "arrow/compute/kernels/vector_topk_benchmark.cc",
    "arrow/compute/key_hash_internal.cc",
    "arrow/compute/key_hash_internal_avx2.cc",
    "arrow/compute/key_hash_test.cc",
    "arrow/compute/key_map_internal.cc",
    "arrow/compute/key_map_internal_avx2.cc",
    "arrow/compute/light_array_internal.cc",
    "arrow/compute/light_array_test.cc",
    "arrow/compute/ordering.cc",
    "arrow/compute/registry.cc",
    "arrow/compute/registry_test.cc",
    "arrow/compute/row/compare_internal.cc",
    "arrow/compute/row/compare_internal_avx2.cc",
    "arrow/compute/row/compare_test.cc",
    "arrow/compute/row/encode_internal.cc",
    "arrow/compute/row/encode_internal_avx2.cc",
    "arrow/compute/row/grouper.cc",
    "arrow/compute/row/grouper_benchmark.cc",
    "arrow/compute/row/grouper_test.cc",
    "arrow/compute/row/row_encoder_internal.cc",
    "arrow/compute/row/row_encoder_internal_test.cc",
    "arrow/compute/row/row_internal.cc",
    "arrow/compute/row/row_test.cc",
    "arrow/compute/test_env.cc",
    "arrow/compute/test_util_internal.cc",
    "arrow/compute/util.cc",
    "arrow/compute/util_avx2.cc",
    "arrow/compute/util_internal.cc",
    "arrow/compute/util_internal_test.cc",
]

compute_hdrs = [
    "arrow/compute/api.h",
    "arrow/compute/api_aggregate.h",
    "arrow/compute/api_scalar.h",
    "arrow/compute/api_vector.h",
    "arrow/compute/cast.h",
    "arrow/compute/cast_internal.h",
    "arrow/compute/exec.h",
    "arrow/compute/exec_internal.h",
    "arrow/compute/expression.h",
    "arrow/compute/expression_internal.h",
    "arrow/compute/function.h",
    "arrow/compute/function_internal.h",
    "arrow/compute/function_options.h",
    "arrow/compute/initialize.h",
    "arrow/compute/kernel.h",
    "arrow/compute/kernels/aggregate_basic_internal.h",
    "arrow/compute/kernels/aggregate_internal.h",
    "arrow/compute/kernels/aggregate_var_std_internal.h",
    "arrow/compute/kernels/base_arithmetic_internal.h",
    "arrow/compute/kernels/chunked_internal.h",
    "arrow/compute/kernels/codegen_internal.h",
    "arrow/compute/kernels/common_internal.h",
    "arrow/compute/kernels/copy_data_internal.h",
    "arrow/compute/kernels/gather_internal.h",
    "arrow/compute/kernels/hash_aggregate_internal.h",
    "arrow/compute/kernels/pivot_internal.h",
    "arrow/compute/kernels/ree_util_internal.h",
    "arrow/compute/kernels/scalar_cast_internal.h",
    "arrow/compute/kernels/scalar_string_internal.h",
    "arrow/compute/kernels/temporal_internal.h",
    "arrow/compute/kernels/test_util_internal.h",
    "arrow/compute/kernels/util_internal.h",
    "arrow/compute/kernels/vector_selection_filter_internal.h",
    "arrow/compute/kernels/vector_selection_internal.h",
    "arrow/compute/kernels/vector_selection_take_internal.h",
    "arrow/compute/kernels/vector_sort_internal.h",
    "arrow/compute/key_hash_internal.h",
    "arrow/compute/key_map_internal.h",
    "arrow/compute/light_array_internal.h",
    "arrow/compute/ordering.h",
    "arrow/compute/registry.h",
    "arrow/compute/registry_internal.h",
    "arrow/compute/row/compare_internal.h",
    "arrow/compute/row/encode_internal.h",
    "arrow/compute/row/grouper.h",
    "arrow/compute/row/grouper_internal.h",
    "arrow/compute/row/row_encoder_internal.h",
    "arrow/compute/row/row_internal.h",
    "arrow/compute/row/row_util_avx2_internal.h",
    "arrow/compute/test_util_internal.h",
    "arrow/compute/type_fwd.h",
    "arrow/compute/util.h",
    "arrow/compute/util_internal.h",
    "arrow/compute/visibility.h",
]

io_srcs = [
    "arrow/io/buffered.cc",
    "arrow/io/buffered_test.cc",
    "arrow/io/caching.cc",
    "arrow/io/compressed.cc",
    "arrow/io/compressed_benchmark.cc",
    "arrow/io/compressed_test.cc",
    "arrow/io/file.cc",
    "arrow/io/file_benchmark.cc",
    "arrow/io/file_test.cc",
    "arrow/io/hdfs.cc",
    "arrow/io/hdfs_internal.cc",
    "arrow/io/hdfs_test.cc",
    "arrow/io/interfaces.cc",
    "arrow/io/memory.cc",
    "arrow/io/memory_benchmark.cc",
    "arrow/io/memory_test.cc",
    "arrow/io/slow.cc",
    "arrow/io/stdio.cc",
    "arrow/io/test_common.cc",
    "arrow/io/transform.cc",
]

io_hdrs = [
    "arrow/io/api.h",
    "arrow/io/buffered.h",
    "arrow/io/caching.h",
    "arrow/io/compressed.h",
    "arrow/io/concurrency.h",
    "arrow/io/file.h",
    "arrow/io/hdfs.h",
    "arrow/io/hdfs_internal.h",
    "arrow/io/interfaces.h",
    "arrow/io/memory.h",
    "arrow/io/mman.h",
    "arrow/io/slow.h",
    "arrow/io/stdio.h",
    "arrow/io/test_common.h",
    "arrow/io/transform.h",
    "arrow/io/type_fwd.h",
    "arrow/io/util_internal.h",
]

ipc_srcs = [
    "arrow/ipc/dictionary.cc",
    "arrow/ipc/endianness_test.cc",
    "arrow/ipc/feather.cc",
    "arrow/ipc/feather_test.cc",
    "arrow/ipc/file_fuzz.cc",
    "arrow/ipc/file_to_stream.cc",
    "arrow/ipc/generate_fuzz_corpus.cc",
    "arrow/ipc/generate_tensor_fuzz_corpus.cc",
    "arrow/ipc/message.cc",
    "arrow/ipc/message_internal_test.cc",
    "arrow/ipc/metadata_internal.cc",
    "arrow/ipc/options.cc",
    "arrow/ipc/read_write_benchmark.cc",
    "arrow/ipc/read_write_test.cc",
    "arrow/ipc/reader.cc",
    "arrow/ipc/stream_fuzz.cc",
    "arrow/ipc/stream_to_file.cc",
    "arrow/ipc/tensor_stream_fuzz.cc",
    "arrow/ipc/tensor_test.cc",
    "arrow/ipc/test_common.cc",
    "arrow/ipc/writer.cc",
]

ipc_hdrs = [
    "arrow/ipc/api.h",
    "arrow/ipc/dictionary.h",
    "arrow/ipc/feather.h",
    "arrow/ipc/message.h",
    "arrow/ipc/metadata_internal.h",
    "arrow/ipc/options.h",
    "arrow/ipc/reader.h",
    "arrow/ipc/reader_internal.h",
    "arrow/ipc/test_common.h",
    "arrow/ipc/type_fwd.h",
    "arrow/ipc/util.h",
    "arrow/ipc/writer.h",
]

testing_srcs = [
    "arrow/testing/examplefs.cc",
    "arrow/testing/fixed_width_test_util.cc",
    "arrow/testing/generator.cc",
    "arrow/testing/generator_test.cc",
    "arrow/testing/gtest_util.cc",
    "arrow/testing/gtest_util_test.cc",
    "arrow/testing/math.cc",
    "arrow/testing/process.cc",
    "arrow/testing/random.cc",
    "arrow/testing/random_test.cc",
    "arrow/testing/util.cc",
]

testing_hdrs = [
    "arrow/testing/async_test_util.h",
    "arrow/testing/builder.h",
    "arrow/testing/examplefs.h",
    "arrow/testing/executor_util.h",
    "arrow/testing/extension_type.h",
    "arrow/testing/fixed_width_test_util.h",
    "arrow/testing/future_util.h",
    "arrow/testing/generator.h",
    "arrow/testing/gtest_compat.h",
    "arrow/testing/gtest_util.h",
    "arrow/testing/matchers.h",
    "arrow/testing/math.h",
    "arrow/testing/process.h",
    "arrow/testing/random.h",
    "arrow/testing/uniform_real.h",
    "arrow/testing/util.h",
    "arrow/testing/visibility.h",
]

util_srcs = [
    "arrow/util/align_util.cc",
    "arrow/util/align_util_test.cc",
    "arrow/util/async_generator_test.cc",
    "arrow/util/async_util.cc",
    "arrow/util/async_util_test.cc",
    "arrow/util/atfork_internal.cc",
    "arrow/util/atfork_test.cc",
    "arrow/util/base64_test.cc",
    "arrow/util/basic_decimal.cc",
    "arrow/util/bit_block_counter.cc",
    "arrow/util/bit_block_counter_benchmark.cc",
    "arrow/util/bit_block_counter_test.cc",
    "arrow/util/bit_run_reader.cc",
    "arrow/util/bit_util.cc",
    "arrow/util/bit_util_benchmark.cc",
    "arrow/util/bit_util_test.cc",
    "arrow/util/bitmap.cc",
    "arrow/util/bitmap_builders.cc",
    "arrow/util/bitmap_ops.cc",
    "arrow/util/bitmap_reader_benchmark.cc",
    "arrow/util/bitmap_test.cc",
    "arrow/util/bpacking.cc",
    "arrow/util/bpacking_benchmark.cc",
    "arrow/util/bpacking_scalar.cc",
    "arrow/util/bpacking_simd_128.cc",
    "arrow/util/bpacking_simd_256.cc",
    "arrow/util/bpacking_simd_avx512.cc",
    "arrow/util/bpacking_test.cc",
    "arrow/util/byte_size.cc",
    "arrow/util/byte_size_test.cc",
    "arrow/util/byte_stream_split_internal.cc",
    "arrow/util/byte_stream_split_internal_avx2.cc",
    "arrow/util/byte_stream_split_test.cc",
    "arrow/util/cache_benchmark.cc",
    "arrow/util/cache_test.cc",
    "arrow/util/cancel.cc",
    "arrow/util/cancel_test.cc",
    "arrow/util/checked_cast_test.cc",
    "arrow/util/compression.cc",
    "arrow/util/compression_benchmark.cc",
    "arrow/util/compression_brotli.cc",
    "arrow/util/compression_bz2.cc",
    "arrow/util/compression_lz4.cc",
    "arrow/util/compression_snappy.cc",
    "arrow/util/compression_test.cc",
    "arrow/util/compression_zlib.cc",
    "arrow/util/compression_zstd.cc",
    "arrow/util/counting_semaphore.cc",
    "arrow/util/counting_semaphore_test.cc",
    "arrow/util/cpu_info.cc",
    "arrow/util/crc32.cc",
    "arrow/util/crc32_test.cc",
    "arrow/util/debug.cc",
    "arrow/util/decimal.cc",
    "arrow/util/decimal_benchmark.cc",
    "arrow/util/decimal_test.cc",
    "arrow/util/delimiting.cc",
    "arrow/util/dict_util.cc",
    "arrow/util/fixed_width_internal.cc",
    "arrow/util/fixed_width_test.cc",
    "arrow/util/float16.cc",
    "arrow/util/float16_test.cc",
    "arrow/util/formatting.cc",
    "arrow/util/formatting_util_test.cc",
    "arrow/util/future.cc",
    "arrow/util/future_test.cc",
    "arrow/util/fuzz_internal.cc",
    "arrow/util/hashing.cc",
    "arrow/util/hashing_benchmark.cc",
    "arrow/util/hashing_test.cc",
    "arrow/util/int_util.cc",
    "arrow/util/int_util_benchmark.cc",
    "arrow/util/int_util_test.cc",
    "arrow/util/io_util.cc",
    "arrow/util/io_util_test.cc",
    "arrow/util/iterator_test.cc",
    "arrow/util/key_value_metadata.cc",
    "arrow/util/key_value_metadata_test.cc",
    "arrow/util/list_util.cc",
    "arrow/util/list_util_test.cc",
    "arrow/util/logger.cc",
    "arrow/util/logger_test.cc",
    "arrow/util/logging.cc",
    "arrow/util/logging_test.cc",
    "arrow/util/machine_benchmark.cc",
    "arrow/util/math_internal.cc",
    "arrow/util/math_test.cc",
    "arrow/util/memory.cc",
    "arrow/util/mutex.cc",
    "arrow/util/queue_benchmark.cc",
    "arrow/util/queue_test.cc",
    "arrow/util/range_benchmark.cc",
    "arrow/util/range_test.cc",
    "arrow/util/ree_util.cc",
    "arrow/util/ree_util_test.cc",
    "arrow/util/reflection_test.cc",
    "arrow/util/rle_bitmap_test.cc",
    "arrow/util/rle_encoding_test.cc",
    "arrow/util/rows_to_batches_test.cc",
    "arrow/util/secure_string.cc",
    "arrow/util/secure_string_test.cc",
    "arrow/util/small_vector_benchmark.cc",
    "arrow/util/small_vector_test.cc",
    "arrow/util/stl_util_test.cc",
    "arrow/util/string.cc",
    "arrow/util/string_test.cc",
    "arrow/util/string_util.cc",
    "arrow/util/task_group.cc",
    "arrow/util/task_group_test.cc",
    "arrow/util/tdigest.cc",
    "arrow/util/tdigest_benchmark.cc",
    "arrow/util/tdigest_test.cc",
    "arrow/util/test_common.cc",
    "arrow/util/thread_pool.cc",
    "arrow/util/thread_pool_benchmark.cc",
    "arrow/util/thread_pool_test.cc",
    "arrow/util/time.cc",
    "arrow/util/time_test.cc",
    "arrow/util/tracing.cc",
    "arrow/util/tracing_internal.cc",
    "arrow/util/tracing_test.cc",
    "arrow/util/trie.cc",
    "arrow/util/trie_benchmark.cc",
    "arrow/util/trie_test.cc",
    "arrow/util/ulp_distance.cc",
    "arrow/util/ulp_distance_test.cc",
    "arrow/util/union_util.cc",
    "arrow/util/unreachable.cc",
    "arrow/util/uri.cc",
    "arrow/util/uri_test.cc",
    "arrow/util/utf8.cc",
    "arrow/util/utf8_util_benchmark.cc",
    "arrow/util/utf8_util_test.cc",
    "arrow/util/value_parsing.cc",
    "arrow/util/value_parsing_benchmark.cc",
    "arrow/util/value_parsing_test.cc",
]

util_hdrs = [
    "arrow/util/algorithm.h",
    "arrow/util/align_util.h",
    "arrow/util/aligned_storage.h",
    "arrow/util/async_generator.h",
    "arrow/util/async_generator_fwd.h",
    "arrow/util/async_util.h",
    "arrow/util/atfork_internal.h",
    "arrow/util/base64.h",
    "arrow/util/basic_decimal.h",
    "arrow/util/benchmark_util.h",
    "arrow/util/binary_view_util.h",
    "arrow/util/bit_block_counter.h",
    "arrow/util/bit_run_reader.h",
    "arrow/util/bit_stream_utils_internal.h",
    "arrow/util/bit_util.h",
    "arrow/util/bitmap.h",
    "arrow/util/bitmap_builders.h",
    "arrow/util/bitmap_generate.h",
    "arrow/util/bitmap_ops.h",
    "arrow/util/bitmap_reader.h",
    "arrow/util/bitmap_visit.h",
    "arrow/util/bitmap_writer.h",
    "arrow/util/bitset_stack_internal.h",
    "arrow/util/bpacking_dispatch_internal.h",
    "arrow/util/bpacking_internal.h",
    "arrow/util/bpacking_scalar_generated_internal.h",
    "arrow/util/bpacking_scalar_internal.h",
    "arrow/util/bpacking_simd512_generated_internal.h",
    "arrow/util/bpacking_simd_internal.h",
    "arrow/util/bpacking_simd_kernel_internal.h",
    "arrow/util/byte_size.h",
    "arrow/util/byte_stream_split_internal.h",
    "arrow/util/cache_internal.h",
    "arrow/util/cancel.h",
    "arrow/util/checked_cast.h",
    "arrow/util/chrono_internal.h",
    "arrow/util/compare.h",
    "arrow/util/compression.h",
    "arrow/util/compression_internal.h",
    "arrow/util/concurrent_map.h",
    "arrow/util/converter.h",
    "arrow/util/counting_semaphore_internal.h",
    "arrow/util/cpu_info.h",
    "arrow/util/crc32.h",
    "arrow/util/date_internal.h",
    "arrow/util/debug.h",
    "arrow/util/decimal.h",
    "arrow/util/decimal_internal.h",
    "arrow/util/delimiting.h",
    "arrow/util/dict_util_internal.h",
    "arrow/util/dispatch_internal.h",
    "arrow/util/double_conversion_internal.h",
    "arrow/util/endian.h",
    "arrow/util/fixed_width_internal.h",
    "arrow/util/float16.h",
    "arrow/util/formatting.h",
    "arrow/util/functional.h",
    "arrow/util/future.h",
    "arrow/util/fuzz_internal.h",
    "arrow/util/hash_util.h",
    "arrow/util/hashing.h",
    "arrow/util/int128_internal.h",
    "arrow/util/int_util.h",
    "arrow/util/int_util_overflow.h",
    "arrow/util/io_util.h",
    "arrow/util/iterator.h",
    "arrow/util/key_value_metadata.h",
    "arrow/util/launder.h",
    "arrow/util/list_util.h",
    "arrow/util/logger.h",
    "arrow/util/logging.h",
    "arrow/util/logging_internal.h",
    "arrow/util/macros.h",
    "arrow/util/map_internal.h",
    "arrow/util/math_constants.h",
    "arrow/util/math_internal.h",
    "arrow/util/memory_internal.h",
    "arrow/util/mutex.h",
    "arrow/util/parallel.h",
    "arrow/util/pcg_random.h",
    "arrow/util/prefetch.h",
    "arrow/util/print_internal.h",
    "arrow/util/queue.h",
    "arrow/util/range.h",
    "arrow/util/ree_util.h",
    "arrow/util/reflection_internal.h",
    "arrow/util/regex.h",
    "arrow/util/rle_bitmap_internal.h",
    "arrow/util/rle_encoding_internal.h",
    "arrow/util/rows_to_batches.h",
    "arrow/util/secure_string.h",
    "arrow/util/simd.h",
    "arrow/util/simdjson_internal.h",
    "arrow/util/slice_util_internal.h",
    "arrow/util/small_vector.h",
    "arrow/util/sort_internal.h",
    "arrow/util/spaced_internal.h",
    "arrow/util/stopwatch_internal.h",
    "arrow/util/string.h",
    "arrow/util/string_util.h",
    "arrow/util/task_group.h",
    "arrow/util/tdigest_internal.h",
    "arrow/util/test_common.h",
    "arrow/util/thread_pool.h",
    "arrow/util/time.h",
    "arrow/util/tracing.h",
    "arrow/util/tracing_internal.h",
    "arrow/util/trie_internal.h",
    "arrow/util/type_fwd.h",
    "arrow/util/type_traits.h",
    "arrow/util/ubsan.h",
    "arrow/util/ulp_distance_internal.h",
    "arrow/util/union_util.h",
    "arrow/util/unreachable.h",
    "arrow/util/uri.h",
    "arrow/util/utf8.h",
    "arrow/util/utf8_internal.h",
    "arrow/util/value_parsing.h",
    "arrow/util/vector.h",
    "arrow/util/visibility.h",
    "arrow/util/windows_compatibility.h",
    "arrow/util/windows_fixup.h",
]

genrule(
    name = "arrow_util_config",
    srcs = ["arrow/util/config.h.cmake"],
    outs = ["arrow/util/config.h"],
    cmd = ("sed " +
           "-e 's/@ARROW_VERSION_MAJOR@/3/g' " +
           "-e 's/@ARROW_VERSION_MINOR@/0/g' " +
           "-e 's/@ARROW_VERSION_PATCH@/0/g' " +
           "-e 's/cmakedefine ARROW_USE_NATIVE_INT128/undef ARROW_USE_NATIVE_INT128/g' " +
           "-e 's/cmakedefine/define/g' " +
           "$< >$@"),
)

generated_hdrs = [
    "arrow/util/config.h",
]

vendored_deps = [
    "//src/arrow/vendored:datetime",
    "//src/arrow/vendored:safeint",
    "//src/arrow/vendored:xxhash",
    ":strptime",
]

bcr_deps = [
    "@boost.multiprecision",
    "@glog",
    "@google_benchmark//:benchmark",
    "@googletest//:gtest",
    # "@flatbuffers",
    # "@safeint",
]

cc_library(
    name = "strptime",
    srcs = ["//src/arrow/vendored/musl:strptime.c"],
    hdrs = ["//src/arrow/vendored:strptime.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "arrow",
    srcs = (
        array_srcs +
        arrow_srcs +
        compute_srcs +
        io_srcs +
        ipc_srcs +
        testing_srcs +
        util_srcs
    ),
    hdrs = (
        array_hdrs +
        arrow_hdrs +
        compute_hdrs +
        generated_hdrs +
        io_hdrs +
        ipc_hdrs +
        testing_hdrs +
        util_hdrs
    ),
    # include_prefix = "arrow",
    includes = [
        ".",
        # "arrow",
        # "arrow/util",
        # "arrow/compute",
        # "arrow/compute/kernels",
    ],
    cxxopts = [
        "-std=c++23",
    #     "-Lutil",
    #     "-Lcompute",
    ],
    deps = (
        vendored_deps +
        bcr_deps
    ),
)
