load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "parquet",
    srcs = [
        "arrow/fuzz_encoding_internal.cc",
        "arrow/fuzz_internal.cc",
        "arrow/path_internal.cc",
        "arrow/reader.cc",
        "arrow/reader_internal.cc",
        "arrow/schema.cc",
        "arrow/schema_internal.cc",
        "arrow/writer.cc",
        "bloom_filter.cc",
        "bloom_filter_reader.cc",
        "bloom_filter_writer.cc",
        "chunker_internal.cc",
        "column_reader.cc",
        "column_scanner.cc",
        "column_writer.cc",
        "decoder.cc",
        "encoder.cc",
        "encryption/encryption.cc",
        "encryption/internal_file_decryptor.cc",
        "encryption/internal_file_encryptor.cc",
        "exception.cc",
        "file_reader.cc",
        "file_writer.cc",
        "geospatial/statistics.cc",
        "geospatial/util_internal.cc",
        "geospatial/util_json_internal.cc",
        "level_comparison.cc",
        "level_conversion.cc",
        "metadata.cc",
        "xxhasher.cc",
        "page_index.cc",
        # "${PARQUET_THRIFT_SOURCE_DIR}/parquet_types.cpp",
        "platform.cc",
        "printer.cc",
        "properties.cc",
        "schema.cc",
        "size_statistics.cc",
        "statistics.cc",
        "stream_reader.cc",
        "stream_writer.cc",
        "types.cc",
    ],
    hdrs = [
        "api/io.h",
        "api/reader.h",
        "api/schema.h",
        "api/writer.h",
        "arrow/fuzz_encoding_internal.h",
        "arrow/fuzz_internal.h",
        "arrow/path_internal.h",
        "arrow/reader.h",
        "arrow/reader_internal.h",
        "arrow/schema.h",
        "arrow/schema_internal.h",
        "arrow/test_util.h",
        "arrow/writer.h",
        "benchmark_util.h",
        "bloom_filter.h",
        "bloom_filter_avx2_internal.h",
        "bloom_filter_block_impl_internal.h",
        "bloom_filter_reader.h",
        "bloom_filter_writer.h",
        "chunker_internal.h",
        "chunker_internal_generated.h",
        "column_page.h",
        "column_reader.h",
        "column_scanner.h",
        "column_writer.h",
        "encoding.h",
        "encryption/crypto_factory.h",
        "encryption/encryption.h",
        "encryption/encryption_internal.h",
        "encryption/file_key_material_store.h",
        "encryption/file_key_unwrapper.h",
        "encryption/file_key_wrapper.h",
        "encryption/file_system_key_material_store.h",
        "encryption/internal_file_decryptor.h",
        "encryption/internal_file_encryptor.h",
        "encryption/key_encryption_key.h",
        "encryption/key_material.h",
        "encryption/key_metadata.h",
        "encryption/key_toolkit.h",
        "encryption/key_toolkit_internal.h",
        "encryption/kms_client.h",
        "encryption/kms_client_factory.h",
        "encryption/local_wrap_kms_client.h",
        "encryption/openssl_internal.h",
        "encryption/test_encryption_util.h",
        "encryption/test_in_memory_kms.h",
        "encryption/two_level_cache_with_expiration.h",
        "encryption/type_fwd.h",
        "exception.h",
        "file_reader.h",
        "file_writer.h",
        "geospatial/statistics.h",
        "geospatial/util_internal.h",
        "geospatial/util_json_internal.h",
        "hasher.h",
        "index_location.h",
        "level_comparison.h",
        "level_comparison_avx2_internal.h",
        "level_comparison_inc.h",
        "level_conversion.h",
        "level_conversion_bmi2_internal.h",
        "level_conversion_inc.h",
        "metadata.h",
        "page_index.h",
        "platform.h",
        "printer.h",
        "properties.h",
        "schema.h",
        "schema_internal.h",
        "size_statistics.h",
        "statistics.h",
        "stream_reader.h",
        "stream_writer.h",
        "test_util.h",
        "thrift_internal.h",
        "type_fwd.h",
        "types.h",
        "visit_type_inline.h",
        "windows_compatibility.h",
        "windows_fixup.h",
        "xxhasher.h",
    ],
    include_prefix = "parquet",
    includes = [
        "parquet/arrow",
    ],
)
