load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "compute_kernels",
    srcs = [
        "aggregate_basic.cc",
        "aggregate_basic.inc.cc",
        "aggregate_basic_avx2.cc",
        "aggregate_basic_avx512.cc",
        "aggregate_mode.cc",
        "aggregate_pivot.cc",
        "aggregate_quantile.cc",
        "aggregate_tdigest.cc",
        "aggregate_test.cc",
        "aggregate_var_std.cc",
        "chunked_internal.cc",
        "codegen_internal.cc",
        "codegen_internal_test.cc",
        "hash_aggregate.cc",
        "hash_aggregate_numeric.cc",
        "hash_aggregate_pivot.cc",
        "pivot_internal.cc",
        "ree_util_internal.cc",
        "scalar_arithmetic.cc",
        "scalar_arithmetic_benchmark.cc",
        "scalar_arithmetic_test.cc",
        "scalar_boolean.cc",
        "scalar_boolean_benchmark.cc",
        "scalar_boolean_test.cc",
        "scalar_cast_benchmark.cc",
        "scalar_cast_boolean.cc",
        "scalar_cast_dictionary.cc",
        "scalar_cast_extension.cc",
        "scalar_cast_internal.cc",
        "scalar_cast_nested.cc",
        "scalar_cast_numeric.cc",
        "scalar_cast_string.cc",
        "scalar_cast_temporal.cc",
        "scalar_cast_test.cc",
        "scalar_compare.cc",
        "scalar_compare_benchmark.cc",
        "scalar_compare_test.cc",
        "scalar_if_else.cc",
        "scalar_if_else_benchmark.cc",
        "scalar_if_else_test.cc",
        "scalar_list_benchmark.cc",
        "scalar_nested.cc",
        "scalar_nested_test.cc",
        "scalar_random.cc",
        "scalar_random_benchmark.cc",
        "scalar_random_test.cc",
        "scalar_round.cc",
        "scalar_round_arithmetic_test.cc",
        "scalar_round_benchmark.cc",
        "scalar_set_lookup.cc",
        "scalar_set_lookup_benchmark.cc",
        "scalar_set_lookup_test.cc",
        "scalar_string_ascii.cc",
        "scalar_string_benchmark.cc",
        "scalar_string_test.cc",
        "scalar_string_utf8.cc",
        "scalar_temporal_benchmark.cc",
        "scalar_temporal_binary.cc",
        "scalar_temporal_test.cc",
        "scalar_temporal_unary.cc",
        "scalar_validity.cc",
        "scalar_validity_test.cc",
        "select_k_test.cc",
        "temporal_internal.cc",
        "test_util_internal.cc",
        "util_internal.cc",
        "vector_array_sort.cc",
        "vector_cumulative_ops.cc",
        "vector_cumulative_ops_test.cc",
        "vector_hash.cc",
        "vector_hash_benchmark.cc",
        "vector_hash_test.cc",
        "vector_nested.cc",
        "vector_nested_test.cc",
        "vector_pairwise.cc",
        "vector_pairwise_test.cc",
        "vector_partition_benchmark.cc",
        "vector_rank.cc",
        "vector_replace.cc",
        "vector_replace_benchmark.cc",
        "vector_replace_test.cc",
        "vector_run_end_encode.cc",
        "vector_run_end_encode_test.cc",
        "vector_select_k.cc",
        "vector_selection.cc",
        "vector_selection_benchmark.cc",
        "vector_selection_filter_internal.cc",
        "vector_selection_internal.cc",
        "vector_selection_take_internal.cc",
        "vector_selection_test.cc",
        "vector_sort.cc",
        "vector_sort_benchmark.cc",
        "vector_sort_test.cc",
        "vector_statistics.cc",
        "vector_statistics_test.cc",
        "vector_swizzle.cc",
        "vector_swizzle_test.cc",
        "vector_topk_benchmark.cc",
    ],
    hdrs = [
        "aggregate_basic_internal.h",
        "aggregate_internal.h",
        "aggregate_var_std_internal.h",
        "base_arithmetic_internal.h",
        "chunked_internal.h",
        "codegen_internal.h",
        "common_internal.h",
        "copy_data_internal.h",
        "gather_internal.h",
        "hash_aggregate_internal.h",
        "pivot_internal.h",
        "ree_util_internal.h",
        "scalar_cast_internal.h",
        "scalar_string_internal.h",
        "temporal_internal.h",
        "test_util_internal.h",
        "util_internal.h",
        "vector_selection_filter_internal.h",
        "vector_selection_internal.h",
        "vector_selection_take_internal.h",
        "vector_sort_internal.h",
    ],
    include_prefix = "arrow/compute/kernels",
    deps = ["@googletest//:gtest"],
)
